#! /bin/sh

panel_progress()
{
    case $1 in
        [0-9])  echo "%{F#$3}%{F#$2}----------" ;;
        1*)     echo "%{F#$3}-%{F#$2}---------" ;;
        2*)     echo "%{F#$3}--%{F#$2}--------" ;;
        3*)     echo "%{F#$3}---%{F#$2}-------" ;;
        4*)     echo "%{F#$3}----%{F#$2}------" ;;
        5*)     echo "%{F#$3}-----%{F#$2}-----" ;;
        6*)     echo "%{F#$3}------%{F#$2}----" ;;
        7*)     echo "%{F#$3}-------%{F#$2}---" ;;
        8*)     echo "%{F#$3}--------%{F#$2}--" ;;
        9*)     echo "%{F#$3}---------%{F#$2}-" ;;
        100)    echo "%{F#$3}----------%{F#$2}" ;;
    esac
}

MONITOR_COUNT=$(bspc query -M | wc -l)

OFFSET=' '

while read -r line; do

    case $line in
        DAT*) ## Clock and date
            timedate=" ${line#???}"
            ;;

        MUS*) ## MPD Music info
            if [ "${line#???}" == "" ]; then
                music=""
            else
                music="  ${line#???}   "
            fi
            ;;

        MAI*) ## Unread inboxes
            mail=" ${line#???}   "
            ;;

        VOL*) ## Volume
            volume=" $(panel_progress ${line#???} FF777777 FFFFFFFF)%{F#FFFFFFFF}   "
            ;;

        DSK*) ## Freediskspace
            freediskspace=" ${line#???}   "
            ;;

        W*) ## BSPWM intenral state
            wminfo=("" "" "")
            currentMonitor=0
            bspwmMessage=${line#?}

            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ]; do
                item=$1
                name=${item#?}
                case $item in
                    [Mm]*) ## Current focused monitor
                        currentMonitor="$name"
                        ;;
                    O*) ## Focused occupied desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    F*) ## Focused free desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    U*) ## Focused urgent desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    o*) ## Occupied resktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                    f*) ## Free desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                    u*) ## Urgent desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                esac
                shift
            done
            ;;


    esac


###########################
# Output to the bar panel #
###########################

if [ "${MONITOR_COUNT}" == "3" ]; then
## Screen 1
printf "%s" "%{S0}%{l}${OFFSET}\
${wminfo[0]}"

printf "%s" "%{S0}%{r}\
Screen 1 right\
${OFFSET}"

## Screen 2
printf "%s" "%{S1}%{l}${OFFSET}\
${wminfo[1]}"

printf "%s" "%{S1}%{r}\
$music\
$freediskspace\
$mail\
$volume\
$timedate\
${OFFSET}"

## Screen 3
printf "%s" "%{S2}%{l}${OFFSET}\
${wminfo[2]}"

printf "%s" "%{S2}%{r}\
Screen 3 right\
${OFFSET}"
fi


if [ "${MONITOR_COUNT}" == "1" ]; then

## Screen 1
printf "%s" "%{S0}%{l}${OFFSET}\
${wminfo[1]}"

printf "%s" "%{S0}%{r}\
$music\
$freediskspace\
$mail\
$volume\
$timedate\
${OFFSET}"

fi

## Send enter
printf "\n"

done
