#!/bin/sh

if [ $(pgrep -cx bspwm_panel) -gt 1 ] ; then
    printf "%s\n" "The bspwm_panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

. bspwm_panel_config

bspc config top_padding $PANEL_HEIGHT

## Subsribe the BSPWM status to the FIFO file.
bspc control --subscribe > "$PANEL_FIFO" &

## Send the current focused window title.
$HOME/.bin/xtitle/bin/xtitle -sf 'T%s' > "$PANEL_FIFO" &

while true; do
    ##echo "DAT" $(panel_render_datetime) > "$PANEL_FIFO"
    ##echo "URM" $(panel_render_unreadmsg) > "$PANEL_FIFO"
    ##echo "MEM" $(panel_render_memoryusage) > "$PANEL_FIFO"
    ##echo "CPU" $(panel_render_cpuusage) > "$PANEL_FIFO"
    ##echo "MUS" $(panel_render_music) > "$PANEL_FIFO"

    ##echo "D" $(panel_clock) > "$PANEL_FIFO"
    ##echo "R" $(panel_process $(panel_use_ram)) > "$PANEL_FIFO"
    ##echo "B" $(panel_process $(panel_battery)) > "$PANEL_FIFO"
    ##echo "C" $(panel_cpu) > "$PANEL_FIFO"
    ##echo "M" $(panel_mpd) > "$PANEL_FIFO"
    sleep 0.7s
done &

cat "$PANEL_FIFO" | \
bspwm_panel_bar | \
$HOME/.bin/bar/bin/bar \
    -g x$PANEL_HEIGHT \
    -F "$COLOR_FOREGROUND" \
    -B "$COLOR_BACKGROUND" \
    -f "-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1,-benis-uushi-medium-r-normal--11-90-75-75-p-58-iso10646-1" | \
while read line; do
    panel_execute $line &
done &

wait
