#!/bin/sh

. bspwm_panel_colors

while read -r line; do
    case $line in
        S*) # clock output
            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
            ;;

        T*) # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
            ;;
    esac
    printf "%s\n" "%{l} $title "
done
