#!/bin/sh

COLOR_BACKGROUND='#BB000000'
COLOR_FOREGROUND='#FFBBBBBB'

COLOR_BLUE='#FF0587A0'

panel_execute()
{
	case $1 in
		"lockscreen") # Start xlock
			eval xlock &
			;;
	esac
}

panel_render_datetime()
{
	# Output: Sun 20-04-14 21:43:00
	echo $(date +'%a %d-%m-%y %H:%M:%S')
}

panel_render_unreadmsg()
{
	# Output email: mail@kevinvdburgt.com
	count_a=$(cat /tmp/inboxunreadcount_mail@kevinvdburgt.com)

	echo "gmail: $count_a zdev: $count_a"
}

panel_render_memoryusage()
{
	echo '__0%%'
}

panel_render_cpuusage()
{
	echo '__0%% __0%% __0%% __0%%'
}

panel_render_music()
{
	echo 'Nightcore - Ladieda'
}

panel_process()
{
    case $1 in
        100) echo "——————————%{F#FF000000}%{F${COLOR_FOREGROUND}}" ;;
     [0-9]) echo "%{F#FF0587a0}%——————————%{F${COLOR_FOREGROUND}}" ;;
        1*) echo "—%{F#FF000000}%—————————%{F${COLOR_FOREGROUND}}" ;;
        2*) echo "——%{F#FF000000}%————————%{F${COLOR_FOREGROUND}}" ;;
        3*) echo "———%{F#FF000000}%———————%{F${COLOR_FOREGROUND}}" ;;
        4*) echo "————%{F#FF000000}%——————%{F${COLOR_FOREGROUND}}" ;;
        5*) echo "—————%{F#FF000000}%—————%{F${COLOR_FOREGROUND}}" ;;
        6*) echo "——————%{F#FF000000}%————%{F${COLOR_FOREGROUND}}" ;;
        7*) echo "———————%{F#FF000000}%———%{F${COLOR_FOREGROUND}}" ;;
        8*) echo "————————%{F#FF000000}%——%{F${COLOR_FOREGROUND}}" ;;
        9*) echo "—————————%{F#FF000000}%—%{F${COLOR_FOREGROUND}}" ;;
    esac
}