#!/bin/sh

. bspwm_panel_config

while read -r line; do
    case $line in
        DAT*) # panel_render_datetime
            var_datetime=" %{F${COLOR_FOREGROUND}}⮃ ⭧ ${line#???}"
            ;;

        MUS*) # panel_render_music
            if [ "${line#???}" == " " ]; then
                var_music=""
            else
                var_music=" ⮃ %{F${COLOR_FOREGROUND}}⭯ ${line#???}"
            fi
            ;;

        T*) # xtitle output
            #var_xtitle="${line#?}"
            ;;

        W*) # bspwm internal state
            bspwminfo=""
            bspwmlayout=" "
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*) # focused occupied desktop
                        bspwminfo="$bspwminfo %{F${COLOR_BLUE}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    F*) # focused free desktop
                        bspwminfo="$bspwminfo %{F${COLOR_BLUE}}$name %{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    U*) # focused urgent desktop
                        bspwminfo="$bspwminfo %{F${COLOR_RED}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    o*) # occupied desktop
                        bspwminfo="$bspwminfo %{F${COLOR_FOREGROUND}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    f*) # free desktop
                        bspwminfo="$bspwminfo %{F${COLOR_FOREGROUND}}$name %{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    u*) # urgent desktop
                        bspwminfo="$bspwminfo %{F${COLOR_RED}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    L*) # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        bspwmlayout=[$layout]
                        #if [ "$layout" == "T" ]; then
                        #    bspwmlayout="%{fa}⮘%{fm}"
                        #else
                        #    bspwmlayout="%{fa}⮛%{fm}"
                        #fi
                        ;;
                esac
                shift
            done
    esac

printf "%s\n" "%{l} \
$bspwmlayout\
$bspwminfo \
$var_xtitle\
\
%{r}\
$var_music\
$var_cpuusage\
$var_memoryusage\
$var_battery\
$var_datetime \
\
%{B${COLOR_BACKGROUND}}%{F${COLOR_BLUE}}⮂%{B${COLOR_BLUE}}%{F${COLOR_WHITE}} \
Arch Linux \
%{A:lockscreen:} ⭤ %{A}\
%{B${COLOR_BACKGROUND}}%{F${COLOR_FOREGROUND}}"
#%{F${COLOR_WHITE}}%{B${COLOR_BLUE}} ARCH LINUX %{F${COLOR_BLUE}}%{B${COLOR_BACKGROUND}}⮀%{F${COLOR_FOREGROUND}}\
#%{F${COLOR_BACKGROUND}}%{B${COLOR_BLUE}}⮀ %{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BLUE}}%{B${COLOR_BACKGROUND}}⮀%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \
#printf "%s\n" "%{l}\
#$wm_infos \
#%{F${COLOR_FOREGROUND}}\
#%{r}⮃ \
#⭯ $var_mpd ⮃ \
#⭟ 0 ⮃ \
#⭮ 0, 2, 3 ⮃ \
#⭥ $var_cpu ⮃ \
#⭦ $var_useram ⮃ \
#%{F#FFFF0000}⮂%{B#FFFF0000}%{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BACKGROUND}}⮂%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \
#%{fa}⮏%{fm} $var_battery ⮃ \
#%{fm}⭧ $var_datetime "

## Powerline example
#%{F#FFFF0000}⮂%{B#FFFF0000}%{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BACKGROUND}}⮂%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \

done


# !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghi
#jklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚ
#ÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪ
#īĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹź
#ŻżŽžſƀƁƂƃƄƅƆƇƈƉƊƋƌƍƎƏƐƑƒƓƔƕƖƗƘƙƚƛƜƝƞƟƠơƢƣƤƥƦƧƨƩƪƫƬƭƮƯưƱƲƳƴƵƶƷƸƹƺƻƼƽƾƿǀǁǂǃǄǅǆǇǈǉǊ
#ǋǌǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟǠǡǢǣǤǥǦǧǨǩǪǫǬǭǮǯǰǱǲǳǴǵǶǷǸǹǺǻǼǽǾǿȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚ
#țȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱȲȳȴȵȶȷȸȹȺȻȼȽȾȿɀɁɂɃɄɅɆɇɈɉɊɋɌɍɎɏɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟɠɡɢɣɤɥɦɧɨɩɪ
#ɫɬɭɮɯɰɱɲɳɴɵɶɷɸɹɺɻɼɽɾɿʀʁʂʃʄʅʆʇʈʉʊʋʌʍʎʏʐʑʒʓʔʕʖʗʘʙʚʛʜʝʞʟʠʡʢʣʤʥʦʧʨʩʪʫʬʭʮʯʰʱʲʳʴʵʶʷʸʹʺ
#ʻʼʽ˂˃˄˅ˆˇˈˉˊˋːˑ˘˙˚˛˜˝˞ˠˤˮ̜̟̠̤̥̪̬̰̹̺̻̼̀́̂̃̄̅̆̇̈̉̊̋̌̍̎̐̑̒̓̔̓̈́̕̚͜͡ͰͱͲͳʹ͵Ͷͷͺͻͼͽ;Ϳ΀΁΄
#΅Ά·ΈΉΊΌΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώϏϐϑϒϓϔϕϖϗ
#ϘϙϚϛϜϝϞϟϠϡϢϣϤϥϦϧϨϩϪϫϬϭϮϯϰϱϲϳϴϵ϶ϷϸϹϺϻϼϽϾϿЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧ
#ШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяѐёђѓєѕіїјљњћќѝўџѠѡѢѣѤѥѦѧѨѩѪѫѬѭѮѯѰѱѲѳѴѵѶѷ
#ѸѹѺѻѼѽѾѿ҂Ґґԅلڡ߸߹ߺ౪ಠಥง฿๑ຈ༼༽ლᕗᕙᴥḀḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯḰḱ
#ḲḳḴḵḶḷḸḹḺḻḼḽḾḿṀṁṂṃṄṅṆṇṈṉṊṋṌṍṎṏṐṑṒṓṔṕṖṗṘṙṚṛṜṝṞṟṠṡṢṣṤṥṦṧṨṩṪṫṬṭṮṯṰṱṲṳṴṵṶṷṸṹṺṻṼṽṾṿẀẁ
#ẂẃẄẅẆẇẈẉẊẋẌẍẎẏẐẑẒẓẔẕồ‐‑‒–—―‖‗‘’‚‛“”„‟†‡•‣․‥…‧‰‱′″‴‵‶‷‸‹›‼‽‾‿⁀⁁⁂⁃⁄⁅⁆⁇⁈⁉⁊⁋⁌⁍⁎⁏⁐⁑⁒⁓
#⁔⁕⁖⁗⁘⁙⁚⁛⁜⁝⁞⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎ₐₑₒₓₔₕₖₗₘₙₚₛₜ₠₡₢₣₤₥₦₧€℃℉№℗™℥Ω℧KÅℯℳℴⅬ←↑→↓
#↔↕↖↗↘↙↚↛↜↝↞↟↠↡↢↣↤↥↦↧↨↩↪↫↬↭↮↯↰↱↲↳↴↵↶↷↸↹↺↻↼↽↾↿⇀⇁⇂⇃⇄⇅⇆⇇⇈⇉⇊⇋⇌⇐⇞⇟⇥⇧⇮⇱⇲⇵⇶⇷⇸⇽⇾⇿∀∁∂∃∄∅∆∇
#∈∉∊∋∌∍∏∐∑−∓∔∕√∛∜∝∞∣∩∫∴≈≖≠≤≥≦≧⊃⊆⊕⊖⊗⊘⊙⌂⌒⌢⌣⌦⌫⎀⎈⎋⏩⏪⏫⏬⏭⏮⏯␣①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳⑴⑵⑶⑷⑸⑹⑺
#⑻⑼⑽⑾⑿⒀⒁⒂⒃⒄⒅⒆⒇⒈⒉⒊⒋⒌⒍⒎⒏⒐⒑⒒⒓⒔⒕⒖⒗⒘⒙⒚⒛⒜⒝⒞⒟⒠⒡⒢⒣⒤⒥⒦⒧⒨⒩⒪⒫⒬⒭⒮⒯⒰⒱⒲⒳⒴⒵▖▗▘▙▚▛▜▝▞▟■□▢▣▤▥▦▧▨▩▪
#▫▬▭▮▯▰▱▲△▴▵▶▷▸▹►▻▼▽▾▿◀◁◂◃◄◅◆◇◈◉◊○◌◍◎●◐◑◒◓◔◕◖◗◘◙◚◛◜◝◞◟◠◡◢◣◤◥◦◧◨◩◪◫◬◭◮◯◰◱◲◳◴◵◶◷◸◹◺
#◻◼◽◾◿☀☁☂☃☄★☆☇☈☉☐☑☖☗☞☰☱☲☳☴☵☶☷☿♀♁♂♠♡♢♣♤♥♦♧♩♪♫♬♭♮♯⚢⚣⚤⚥⚦⚧⚨⚩✈✓✔✕✖✗✘✚✛✜✝✞✟✠✡✤✥✦✧✩✪✫✳✶✿
#❁❏❐❑❒❛❜❝❞❟❠❤❥❦❬❭❮❯❰❱➊➋➌➍➎➏➐➑➒➓➔➕➖➗➘➙➚➛⟨⟩⠀⠁⠂⠃⠄⠅⠆⠇⠈⠉⠊⠋⠌⠍⠎⠏⠐⠑⠒⠓⠔⠕⠖⠗⠘⠙⠚⠛⠜⠝⠞⠟⠠⠡⠢⠣⠤⠥⠦⠧
#⠨⠩⠪⠫⠬⠭⠮⠯⠰⠱⠲⠳⠴⠵⠶⠷⠸⠹⠺⠻⠼⠽⠾⠿⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷
#⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇
#⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿
# ⭐ ⭟ ⭠ ⭡ ⭢ ⭣ ⭤ ⭥ ⭦  ⭧ ⭨ ⭩ ⭪ ⭫ ⭬ ⭭ ⭮ ⭯ ⮀ ⮁ ⮂ ⮃ ⱱ ⸘
# ⮎ ⮒ ⮏ ⮑ ⮐
# ⮜ ⮞ ⮟ ⮝
#⮷ ⮸ ⮹
# ⮡ ⮦ ⮰
# ⮤ ⮩
# ⮛ ⮨ ⮘ ⮙ ⮚ ⮧ ⮽
# ⮾ ⮿ ⯀ ⯁ ⯂ ⯃ ⯄ ⯅ ⯆ ⯇ ⯈
# ⮕ ⮓ ⮔ ⮲ ⮳
# ⮫ ⮬ ⮭ ⮮ ⮯ 
# ⮴ ⮵
# ⮗ ⮢
# ⮖ ⮠ ⮣ ⮪ ⮥ ⮺ ⮻ ⮼