#!/bin/sh

if [ $(pgrep -cx bspwm_panel) -gt 1 ] ; then
    printf "%s\n" "The bspwm_panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

. bspwm_panel_config

bspc config top_padding $PANEL_HEIGHT

## Subsribe the BSPWM status to the FIFO file.
bspc control --subscribe > "$PANEL_FIFO" &

## Send the current focused window title.
$HOME/.bin/xtitle/bin/xtitle -sf 'T%s' > "$PANEL_FIFO" &

while true; do
    echo "DAT" $(panel_render_datetime) > "$PANEL_FIFO"
    echo "MUS" "$(panel_render_music)" > "$PANEL_FIFO"

    sleep 0.7s
done &

while true; do
    #echo "ACC" $(panel_render_battery) > "$PANEL_FIFO" # LAPTOP ONLY !

    sleep 5.0s
done &

cat "$PANEL_FIFO" | \
bspwm_panel_bar | \
$HOME/.bin/bar/bin/bar \
    -g x$PANEL_HEIGHT \
    -F "$COLOR_FOREGROUND" \
    -B "$COLOR_BACKGROUND" \
    -f "-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1,-benis-uushi-medium-r-normal--11-90-75-75-p-58-iso10646-1" | \
while read line; do
    panel_execute $line
done &

wait
