#!/bin/sh

. bspwm_panel_config

while read -r line; do
    case $line in
        DAT*) # panel_render_datetime
            var_datetime=" ⮃ %{F${COLOR_BLUE}}⭧ %{F${COLOR_FOREGROUND}}${line#???}"
            ;;

        URM*) # panel_render_unreadmsg
            var_unreadmsg=" ⮃ %{F${COLOR_BLUE}}⭮ %{F${COLOR_FOREGROUND}}${line#???}"
            ;;

        MEM*) # panel_render_memoryusage
            var_memoryusage=" ⮃ %{F${COLOR_BLUE}}⭦ %{F${COLOR_FOREGROUND}}${line#???}"
            ;;

        CPU*) # panel_render_cpuusage
            var_cpuusage=" ⮃ %{F${COLOR_BLUE}}⭥ %{F${COLOR_FOREGROUND}}${line#???}"
            ;;

        MUS*) # panel_render_music
            var_music=" ⮃ %{F${COLOR_BLUE}}⭯ %{F${COLOR_FOREGROUND}}${line#???}"
            ;;

        T*) # xtitle output
            var_xtitle="${line#?}"
            ;;

        W*) # bspwm internal state
            bspwminfo=""
            bspwmlayout="[ ]"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*) # focused occupied desktop
                        bspwminfo="$bspwminfo %{F${COLOR_BLUE}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    F*) # focused free desktop
                        bspwminfo="$bspwminfo %{F${COLOR_BLUE}}$name %{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    U*) # focused urgent desktop
                        bspwminfo="$bspwminfo %{F${COLOR_RED}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    o*) # occupied desktop
                        bspwminfo="$bspwminfo %{F${COLOR_FOREGROUND}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    f*) # free desktop
                        bspwminfo="$bspwminfo %{F${COLOR_FOREGROUND}}$name %{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    u*) # urgent desktop
                        bspwminfo="$bspwminfo %{F${COLOR_RED}}$name⠁%{F${COLOR_FOREGROUND}}⮁"
                        ;;

                    L*) # layout
                        bspwmlayout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        ;;
                esac
                shift
            done
    esac

printf "%s\n" "%{l}\
%{A:lockscreen:} ⭤ %{A}\
[$bspwmlayout]$bspwminfo $var_xtitle\
INTERNET ⮁\
%{r}\
\
$var_music\
$var_cpuusage\
$var_memoryusage\
$var_unreadmsg\
$var_datetime\
 "

#%{F${COLOR_BACKGROUND}}%{B${COLOR_BLUE}}⮀ %{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BLUE}}%{B${COLOR_BACKGROUND}}⮀%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \
#printf "%s\n" "%{l}\
#$wm_infos \
#%{F${COLOR_FOREGROUND}}\
#%{r}⮃ \
#⭯ $var_mpd ⮃ \
#⭟ 0 ⮃ \
#⭮ 0, 2, 3 ⮃ \
#⭥ $var_cpu ⮃ \
#⭦ $var_useram ⮃ \
#%{F#FFFF0000}⮂%{B#FFFF0000}%{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BACKGROUND}}⮂%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \
#%{fa}⮏%{fm} $var_battery ⮃ \
#%{fm}⭧ $var_datetime "

## Powerline example
#%{F#FFFF0000}⮂%{B#FFFF0000}%{F#FFFFFFFF} POWERLINE TEXT HERE %{F${COLOR_BACKGROUND}}⮂%{F${COLOR_FOREGROUND}}%{B${COLOR_BACKGROUND}} \

done


# !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghi
#jklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚ
#ÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪ
#īĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹź
#ŻżŽžſƀƁƂƃƄƅƆƇƈƉƊƋƌƍƎƏƐƑƒƓƔƕƖƗƘƙƚƛƜƝƞƟƠơƢƣƤƥƦƧƨƩƪƫƬƭƮƯưƱƲƳƴƵƶƷƸƹƺƻƼƽƾƿǀǁǂǃǄǅǆǇǈǉǊ
#ǋǌǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟǠǡǢǣǤǥǦǧǨǩǪǫǬǭǮǯǰǱǲǳǴǵǶǷǸǹǺǻǼǽǾǿȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚ
#țȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱȲȳȴȵȶȷȸȹȺȻȼȽȾȿɀɁɂɃɄɅɆɇɈɉɊɋɌɍɎɏɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟɠɡɢɣɤɥɦɧɨɩɪ
#ɫɬɭɮɯɰɱɲɳɴɵɶɷɸɹɺɻɼɽɾɿʀʁʂʃʄʅʆʇʈʉʊʋʌʍʎʏʐʑʒʓʔʕʖʗʘʙʚʛʜʝʞʟʠʡʢʣʤʥʦʧʨʩʪʫʬʭʮʯʰʱʲʳʴʵʶʷʸʹʺ
#ʻʼʽ˂˃˄˅ˆˇˈˉˊˋːˑ˘˙˚˛˜˝˞ˠˤˮ̜̟̠̤̥̪̬̰̹̺̻̼̀́̂̃̄̅̆̇̈̉̊̋̌̍̎̐̑̒̓̔̓̈́̕̚͜͡ͰͱͲͳʹ͵Ͷͷͺͻͼͽ;Ϳ΀΁΄
#΅Ά·ΈΉΊΌΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώϏϐϑϒϓϔϕϖϗ
#ϘϙϚϛϜϝϞϟϠϡϢϣϤϥϦϧϨϩϪϫϬϭϮϯϰϱϲϳϴϵ϶ϷϸϹϺϻϼϽϾϿЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧ
#ШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяѐёђѓєѕіїјљњћќѝўџѠѡѢѣѤѥѦѧѨѩѪѫѬѭѮѯѰѱѲѳѴѵѶѷ
#ѸѹѺѻѼѽѾѿ҂Ґґԅلڡ߸߹ߺ౪ಠಥง฿๑ຈ༼༽ლᕗᕙᴥḀḁḂḃḄḅḆḇḈḉḊḋḌḍḎḏḐḑḒḓḔḕḖḗḘḙḚḛḜḝḞḟḠḡḢḣḤḥḦḧḨḩḪḫḬḭḮḯḰḱ
#ḲḳḴḵḶḷḸḹḺḻḼḽḾḿṀṁṂṃṄṅṆṇṈṉṊṋṌṍṎṏṐṑṒṓṔṕṖṗṘṙṚṛṜṝṞṟṠṡṢṣṤṥṦṧṨṩṪṫṬṭṮṯṰṱṲṳṴṵṶṷṸṹṺṻṼṽṾṿẀẁ
#ẂẃẄẅẆẇẈẉẊẋẌẍẎẏẐẑẒẓẔẕồ‐‑‒–—―‖‗‘’‚‛“”„‟†‡•‣․‥…‧‰‱′″‴‵‶‷‸‹›‼‽‾‿⁀⁁⁂⁃⁄⁅⁆⁇⁈⁉⁊⁋⁌⁍⁎⁏⁐⁑⁒⁓
#⁔⁕⁖⁗⁘⁙⁚⁛⁜⁝⁞⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎ₐₑₒₓₔₕₖₗₘₙₚₛₜ₠₡₢₣₤₥₦₧€℃℉№℗™℥Ω℧KÅℯℳℴⅬ←↑→↓
#↔↕↖↗↘↙↚↛↜↝↞↟↠↡↢↣↤↥↦↧↨↩↪↫↬↭↮↯↰↱↲↳↴↵↶↷↸↹↺↻↼↽↾↿⇀⇁⇂⇃⇄⇅⇆⇇⇈⇉⇊⇋⇌⇐⇞⇟⇥⇧⇮⇱⇲⇵⇶⇷⇸⇽⇾⇿∀∁∂∃∄∅∆∇
#∈∉∊∋∌∍∏∐∑−∓∔∕√∛∜∝∞∣∩∫∴≈≖≠≤≥≦≧⊃⊆⊕⊖⊗⊘⊙⌂⌒⌢⌣⌦⌫⎀⎈⎋⏩⏪⏫⏬⏭⏮⏯␣①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳⑴⑵⑶⑷⑸⑹⑺
#⑻⑼⑽⑾⑿⒀⒁⒂⒃⒄⒅⒆⒇⒈⒉⒊⒋⒌⒍⒎⒏⒐⒑⒒⒓⒔⒕⒖⒗⒘⒙⒚⒛⒜⒝⒞⒟⒠⒡⒢⒣⒤⒥⒦⒧⒨⒩⒪⒫⒬⒭⒮⒯⒰⒱⒲⒳⒴⒵▖▗▘▙▚▛▜▝▞▟■□▢▣▤▥▦▧▨▩▪
#▫▬▭▮▯▰▱▲△▴▵▶▷▸▹►▻▼▽▾▿◀◁◂◃◄◅◆◇◈◉◊○◌◍◎●◐◑◒◓◔◕◖◗◘◙◚◛◜◝◞◟◠◡◢◣◤◥◦◧◨◩◪◫◬◭◮◯◰◱◲◳◴◵◶◷◸◹◺
#◻◼◽◾◿☀☁☂☃☄★☆☇☈☉☐☑☖☗☞☰☱☲☳☴☵☶☷☿♀♁♂♠♡♢♣♤♥♦♧♩♪♫♬♭♮♯⚢⚣⚤⚥⚦⚧⚨⚩✈✓✔✕✖✗✘✚✛✜✝✞✟✠✡✤✥✦✧✩✪✫✳✶✿
#❁❏❐❑❒❛❜❝❞❟❠❤❥❦❬❭❮❯❰❱➊➋➌➍➎➏➐➑➒➓➔➕➖➗➘➙➚➛⟨⟩⠀⠁⠂⠃⠄⠅⠆⠇⠈⠉⠊⠋⠌⠍⠎⠏⠐⠑⠒⠓⠔⠕⠖⠗⠘⠙⠚⠛⠜⠝⠞⠟⠠⠡⠢⠣⠤⠥⠦⠧
#⠨⠩⠪⠫⠬⠭⠮⠯⠰⠱⠲⠳⠴⠵⠶⠷⠸⠹⠺⠻⠼⠽⠾⠿⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷
#⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇
#⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿
# ⭐ ⭟ ⭠ ⭡ ⭢ ⭣ ⭤ ⭥ ⭦  ⭧ ⭨ ⭩ ⭪ ⭫ ⭬ ⭭ ⭮ ⭯ ⮀ ⮁ ⮂ ⮃ ⱱ ⸘
# ⮎ ⮒ ⮏ ⮑ ⮐
# ⮜ ⮞ ⮟ ⮝
#⮷ ⮸ ⮹
# ⮡ ⮦ ⮰
# ⮤ ⮩
# ⮛ ⮨ ⮘ ⮙ ⮚ ⮧ ⮽
# ⮾ ⮿ ⯀ ⯁ ⯂ ⯃ ⯄ ⯅ ⯆ ⯇ ⯈
# ⮕ ⮓ ⮔ ⮲ ⮳
# ⮫ ⮬ ⮭ ⮮ ⮯ 
# ⮴ ⮵
# ⮗ ⮢
# ⮖ ⮠ ⮣ ⮪ ⮥ ⮺ ⮻ ⮼