#!/bin/sh

COLOR_BACKGROUND='#DD000000'
COLOR_FOREGROUND='#FFBBBBBB'

COLOR_BLUE='#FF0587A0'
COLOR_RED='#FFFF0000'
COLOR_WHITE='#FFFFFFFF'

panel_execute()
{
	case $1 in
		"lockscreen") # Start xlock
			xlock &
			;;
	esac
}

panel_render_datetime()
{
	# Output: Sun 20-04-14 21:43:00
	echo $(date +'%a %d-%m-%y %H:%M:%S')
}

panel_render_battery()
{
	battery=$(acpi --battery | cut -d' ' -f3 | sed 's/,//')
	if [ "$battery" == "" ]; then
		echo 'A0'
	elif [ "$battery" == "Charging" ]; then
		echo 'C1'
	elif [ "$battery" == "Discharging" ]; then
		echo 'D2'
	else
		echo 'N3'
	fi
}

panel_render_music()
{
	echo $(ncmpcpp --now-playing '%t - %a')
}

panel_render_twitch()
{
	echo $(curl -s http://localhost/twitch.php)
}

panel_process()
{
	echo $1
    case $1 in
        100) echo "%{F#$3}——————————%{F#$2}" ;;
     [0-9]) echo "%{F#$3}%{F#$2}%——————————" ;;
        1*) echo "%{F#$3}—%{F#$2}%—————————" ;;
        2*) echo "%{F#$3}——%{F#$2}%————————" ;;
        3*) echo "%{F#$3}———%{F#$2}%———————" ;;
        4*) echo "%{F#$3}————%{F#$2}%——————" ;;
        5*) echo "%{F#$3}—————%{F#$2}%—————" ;;
        6*) echo "%{F#$3}——————%{F#$2}%————" ;;
        7*) echo "%{F#$3}———————%{F#$2}%———" ;;
        8*) echo "%{F#$3}————————%{F#$2}%——" ;;
        9*) echo "%{F#$3}—————————%{F#$2}%—" ;;
    esac
}
