#!/bin/bash
DFDIR=$HOME/.dotfiles/

## Executable scripts, exclude folders wich contains binary files
find $HOME/.bin/ -maxdepth 1 -type f -exec cp -rvu {} ${DFDIR}.bin/ \;

## Configuration files and folders
cp -rvu $HOME/.config/bspwm ${DFDIR}.config/
cp -rvu $HOME/.config/sxhkd ${DFDIR}.config/
cp -rvu $HOME/.config/compton ${DFDIR}.config/

## Files in my home root
cp -rvu $HOME/.Xresources ${DFDIR}
cp -rvu $HOME/.xinitrc ${DFDIR}
cp -rvu $HOME/.bash_profile ${DFDIR}



## Folders
#cp -rvu                 ~/.bin/                         ${DFDIR

## Files
#cp -rvu                 ~/.Xresources                   ${DFDIR}
#cp -rvu                 ~/.xinitrc                      ${DFDIR}
#cp -rvu                 ~/.bashrc                       ${DFDIR}
#cp -rvu                 ~/.vimrc                        ${DFDIR}
