#!/bin/bash
DFDIR=~/.dotfiles/

## Folders
cp -rvu                 ~/.bin/                         ${DFDIR}

## Files
cp -rvu                 ~/.Xresources                   ${DFDIR}
cp -rvu                 ~/.xinitrc                      ${DFDIR}
cp -rvu                 ~/.bashrc                       ${DFDIR}
cp -rvu                 ~/.vimrc                        ${DFDIR}
