#! /bin/sh
DIR_DOTFILES=$HOME/.dotfiles/

savefiles()
{
    ## $HOME/.bin/* (Exclude folders)
    rsync --progress --human-readable --update --checksum \
        $HOME/.bin/* \
        "$DIR_DOTFILES".bin/

    ## Files in the home folder
    rsync --progress --human-readable --update --checksum \
        $HOME/{.Xresources,.xinitrc,.bash_profile,.gtkrc-2.0} \
        "$DIR_DOTFILES"

    ## Configuration files in the .config folder
    rsync --progress --human-readable --update --checksum \
        $HOME/.config/{bspwm,sxhkd,wallpaper.jpg,gtk-3.0} \
        "$DIR_DOTFILES".config/
}

restorefiles()
{
    ## $HOME/.bin/* (Exclude folders)
    rsync --progress --human-readable --update --checksum \
        "$DIR_DOTFILES".bin/* \
        $HOME/.bin/

    ## Files in the home folder
    rsync --progress --human-readable --update --checksum \
        "$DIR_DOTFILES"{.Xresources,.xinitrc,.bash_profile,.gtkrc-2.0} \
        $HOME/

    ## Configuration files in the .config folder
    rsync --progress --human-readable --update --checksum \
        "$DIR_DOTFILES".config/{bspwm,sxhkd,wallpaper.jpg,gtk-3.0} \
        $HOME/.config/

}

gitpull()
{
    CURDIR=$(pwd)
    cd $DIR_DOTFILES
    git pull
    cd $CURDIR

    restorefiles
}

gitpush()
{
    if [[ -z "$1" ]]; then
        echo "Usage dofilesupdate push <comment>"
        exit 1
    fi

    savefiles

    CURDIR=$(pwd)
    cd $DIR_DOTFILES
    git add .
    git commit -m "$1"
    git push
    cd $CURDIR
}

case $1 in
    "push")
        gitpush $2
        ;;
    
    "pull")
        gitpull
        ;;

    *)
        echo "Usage $1 <push|pull>"
        exit 1
        ;;
esac
