#!/bin/bash

stream_twitch()
{
    # Find stream key for twitch
    if [ -f $HOME/.twitch_key ]; then
        STREAM_KEY=$(cat $HOME/.twitch_key)
    elif [ -f $HOME/.config/twitch_key ]; then
        STREAM_KEY=$(cat $HOME/.config/twitch_key)
    else
        echo "No twitch stream key found. Please create a file in your home directory called '.twitch_key'"
        exit 1
    fi

    ffmpeg \
        -f alsa \
        -i pulse \
        -f x11grab \
        -s 1920x1080 \
        -r 30 \
        -i :0.0 \
        -c:v libx264 \
        -preset fast \
        -pix_fmt yuv420p \
        -s 1920x1080 \
        -c:a libmp3lame \
        -ar 44100 \
        -threads 0 \
        -b:v 3072k \
        -b:a 128k \
        -af aresample=async=24000:first_pts=0 \
        -bufsize 1024k \
        -f flv \
        "rtmp://live-ams.twitch.tv/app/$STREAM_KEY"

}

case $1 in
    "twitch")
        stream_twitch
        ;;
esac
