#!/bin/bash

showversions()
{
	echo 'Usage: minecraft <version>'
	echo
	echo 'Versions:'
	echo ' - vanilla'
}

if [ -z "$1" ]; then 
    showversions
    exit 1
fi

case $1 in
	"vanilla")
		java -jar $HOME/.bin/minecraft_vanilla/Minecraft.jar
		;;

	*)
		showversions
		exit 1
		;;
esac
