#!/bin/bash

volume_increase()
{
    # G930 Headset
    ponymix -d "G930" increase 2
}

volume_decrease()
{
    # G930 Headset
    ponymix -d "G930" decrease 2
}

volume_mute()
{
    # G930 Headset
    ponymix -d "G930" toggle
}

volume_get()
{
    # G930 Headset
    ponymix -d "G930" get-volume
}

case $1 in
    "up") 
        volume_increase
        ;;

    "down")
        volume_decrease
        ;;

    "mute")
        volume_mute
        ;;

    "volume")
        volume_get
        ;;
esac
