#!/bin/bash

volume_increase()
{
    if [ ponymix list | grep "G930" ]; then
        # G930 Headset
        ponymix -d "G930" increase 2
    fi
}

volume_decrease()
{
    if [ ponymix list | grep "G930" ]; then
        # G930 Headset
        ponymix -d "G930" decrease 2
    fi
}

volume_mute()
{
    if [ ponymix list | grep "G930" ]; then
        # G930 Headset
        ponymix -d "G930" toggle
    fi
}

volume_get()
{
    if [ ponymix list | grep "G930" ]; then
        # G930 Headset
        ponymix -d "G930" get-volume
    fi
}

case $1 in
    "up") 
        volume_increase
        ;;

    "down")
        volume_decrease
        ;;

    "mute")
        volume_mute
        ;;

    "volume")
        volume_get
        ;;
esac
