#!/bin/bash

source config

ffmpeg \
    -f x11grab -s $1 -r 30 -i :0.0 \
    -vb 128k -pix_fmt yuv420p -vcodec libx264 \
    -f alsa -acodec libmp3lame \
    -preset ultrafast -b:v 1024k -b:a 128k \
    -f flv "rtmp://live.justin.tv/app/$DOTF_TWITCHKEY"
                    
