#! /bin/sh

bspc monitor -d I II III IV

bspc config border_width                2
bspc config window_gap                  12
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config normal_border_color	        "#5E5E5E"
bspc config focused_border_color        "#111111"
bspc config presel_border_color         "#111111"

bspc config normal_frame_opacity	0.0
bspc config focused_frame_opacity       0.05

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
