#!/bin/bash

DFDIR=~/.dotfiles/


cp -rvu ~/Scripts ${DFDIR}
cp -rvu ~/.i3 ${DFDIR}
cp -rvu ~/.asoundrc ${DFDIR}
cp -rvu ~/.Xresources ${DFDIR}
cp -rvu ~/.xinitrc ${DFDIR}
cp -rvu ~/.bashrc ${DFDIR}
cp -rvu ~/.vimrc ${DFDIR}

# Weechat Configs
cp -rvu ~/.weechat/weechat.conf ${DFDIR}.weechat/

# GTK Configs
cp -rvu ~/.gtkrc-2.0 ${DFDIR}                                       # GTK 2.0
cp -rvu ~/.config/gtk-3.0/settings.ini ${DFDIR}.config/gtk-3.0/     #GTK 3.0
